uxlabs/apps/contacts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^contacto/$', views.contacto, name='contacto'),
]

uxlabs/apps/info/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^nosotros/$', views.nosotros, name='nosotros'),
    url(r'^legal/$', views.legal, name='legal'),
]

uxlabs/apps/websites/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^websites/$', views.websites, name='websites'),
    url(r'^websites/(?P<slug>[-\w]+)/$', views.detalle, name='detalle'),
]

uxlabs/uxlabs/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.contacts.urls', namespace='contacts')),
    url(r'^', include('apps.websites.urls', namespace='websites')),
    url(r'^', include('apps.info.urls', namespace='info')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uxlabs/apps/contacts/models.py
from datetime import datetime
from django.db import models
from . import choices

class Contacto(models.Model):
    fecha = models.DateTimeField('Fecha/Hora', default=datetime.now)
    estado = models.CharField('Estado', max_length=1, choices=choices.ESTADO_FORMULARIO_CONTACTO, default=choices.ESTADO_PENDIENTE)
    nombres = models.CharField('Nombres', max_length=32)
    email = models.EmailField('Email')
    asunto = models.CharField('Asunto', max_length=48)
    detalle = models.TextField('Detalle')

    def __str__(self):
        return self.nombres

    class Meta:
        verbose_name = 'Formulario de Contacto'
        verbose_name_plural = 'Formularios de Contacto'

uxlabs/apps/core/models.py
from django.db import models
from uuslug import uuslug


class PositionModel(models.Model):
    position = models.SmallIntegerField('Posición', default=0)

    class Meta:
        abstract = True
        ordering = ['position']


class SlugModel(models.Model):
    nombre = models.CharField('Nombre', max_length=64)
    slug = models.SlugField('slug', max_length=64, blank=True)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.nombre, instance=self)
        super(SlugModel, self).save(*args, **kwargs)

uxlabs/apps/info/models.py
from django.db import models

from apps.core.models import PositionModel


class SeccionNosotros(PositionModel):
    titulo = models.CharField('Título', max_length=64)
    detalle = models.TextField('Detalle')

    class Meta:
        verbose_name = 'Bloque de sección Nosotros'
        verbose_name_plural = 'Sección Nosotros'
        ordering = ['position']

    def __str__(self):
        return self.titulo


class SeccionLegal(PositionModel):
    titulo = models.CharField('Título', max_length=64)
    detalle = models.TextField('Detalle')

    class Meta:
        verbose_name = 'Bloque de sección Lega'
        verbose_name_plural = 'Sección Legal'
        ordering = ['position']

    def __str__(self):
        return self.titulo

uxlabs/apps/websites/models.py
from datetime import date

from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager
from colorfield.fields import ColorField

from apps.core.models import PositionModel, SlugModel


class Categoria(models.Model):
    nombre = models.CharField('Categoría', max_length=64)

    def __str__(self):
        return self.nombre


class Web(SlugModel):
    categoria = models.ManyToManyField(Categoria)
    resumen = models.TextField('Resumen', blank=True)
    detalle = models.TextField('Detalle', blank=True)
    enlace = models.URLField('Enlace', blank=True)
    fecha_de_revision = models.DateField('Fecha de revisión', blank=True, default=date.today)
    etiquetas = TaggableManager()

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('websites:detalle', kwargs={'slug': self.slug})

    def main_img(self):
        ''' Imagen principal '''
        return self.galeria.all().first()


class WebImagen(models.Model):
    web = models.ForeignKey(Web, related_name='galeria')
    titulo = models.CharField('Título', max_length=64)
    imagen = models.ImageField('Imagen', upload_to='galeria')

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Galería'

    def __str__(self):
        return self.titulo


class WebColor(PositionModel):
    web = models.ForeignKey(Web, related_name='paleta_de_colores')
    color = ColorField(default='#FFFFFF')

    class Meta:
        verbose_name = 'Color'
        verbose_name_plural = 'Paleta de colores'

    def __unicode__(self):
        return self.color

uxlabs/apps/contacts/forms.py
from django import forms
from . import models


class ContactoForm(forms.ModelForm):

    class Meta:
        model = models.Contacto
        fields = ('nombres', 'email', 'asunto', 'detalle')

uxlabs/apps/contacts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import ContactoForm
from .models import Contacto


def contacto(request):

    if request.method == 'POST':
        form = ContactoForm(request.POST)

        if form.is_valid():
            form.save()
    else:
        form = ContactoForm()
    return render(request, 'contacts/contacto.html', locals())

uxlabs/apps/info/views.py
from django.shortcuts import render

from .models import SeccionNosotros, SeccionLegal


def nosotros(request):
    secciones = SeccionNosotros.objects.all().order_by('position')

    return render(request, 'info/nosotros.html', locals())


def legal(request):
    secciones = SeccionLegal.objects.all().order_by('position')

    return render(request, 'info/legal.html', locals())

uxlabs/apps/websites/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from pure_pagination import Paginator

from .models import Web, Categoria


def home(request):
    PAGINACION = 6
    destacado = Web.objects.all().order_by('fecha_de_revision').first()
    webs = Web.objects.all().order_by('fecha_de_revision')[:PAGINACION]

    return render(request, 'web/home.html', locals())


def websites(request):
    """
        Retorna la lista de websites
    """
    WEBS_POR_PAGINA = 12
    webs = Web.objects.all()

    # parámetros GET
    q_categoria = request.GET.get('categoria', '').strip()
    q = request.GET.get('q', '')

    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        page = 1

    categorias = Categoria.objects.all()

    if q_categoria:
        try:
            categoria = Categoria.objects.get(nombre=q_categoria)
        except:
            categoria = None

        if categoria:
            webs = webs.filter(categoria=categoria)

    # búsqueda
    if q and len(q) > 2:
        q1 = Q(nombre__icontains=q)
        q2 = Q(detalle__icontains=q)
        webs = webs.filter(q1 | q2 )

    webs = webs.order_by('fecha_de_revision')

    # paginacion
    p = Paginator(webs, WEBS_POR_PAGINA, request=request)
    lista_webs = p.page(page)


    return render(request, 'web/websites.html', locals())


def detalle(request, slug):
    """
        Retorna el detalle de un website
    """
    web = get_object_or_404(Web, slug=slug)

    return render(request, 'web/detalle.html', locals())

uxlabs/templates/common/_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>UXlabs</title>

    <link href="https://fonts.googleapis.com/css?family=Dosis:400,600,700|Open+Sans:300,400,700" rel="stylesheet">
    <link rel='stylesheet' href='{% static "css/main.css" %}'>
</head>

<body class='{% block classbody %}{% endblock classbody %}'>
    {% include 'common/_header.html' %}
    {% block content %}{% endblock content %}
    {% include 'common/_footer.html' %}
</body>
</html>

uxlabs/templates/common/_footer.html
{% load static %}
<footer>
    <div class='footer_container columns'>
        <figure class='col-2 copy'>
            <img clasS='logo' src='{% static "img/isotipo.png" %}' alt='isotipo uxlabs'>
            <figcaption>uxlabs - 2016</figcaption>
        </figure>

        <div class='col-2'>
            <h3>INFORMACIÓN</h3>
            <ul>
                <li class='nav-link'><a href="">nosotros</a></li>
                <li class='nav-link'><a href="">proceso de selección</a></li>
                <li class='nav-link'><a href="">términos legales</a></li>
                <li class='nav-link'><a href="">contáctanos</a></li>
            </ul>
        </div>

        <nav class="col-2">
            <h3>GALERÍA</h3>
            <ul>
                <li class='nav-link'><a href="">categorías</a></li>
                <li class='nav-link'><a ref="">etiquetas</a></li>
                <li class='nav-link'><a href="">colores</a></li>
            </ul>
        </nav>

        <nav class="form_suscripcion col-3">
            <h3>SUSCRÍBETE</h3>

            <input class='form_control' type='email' placeholder='anakin@skywalker.com'>
            <button class='btn btn_1' type='submit'>suscríbeme!</button>
            <p>recibe las últimas novedades.
            <br>nada de spam, lo prometemos !</p>
        </nav>

        <div class='col-3'>
            <span>también estamos en:</span>

            <div class='social'>
                <img src='{% static "img/icon_mail.png" %}' alt='icon email' class='icon' width='32' height='32'>
                <img src='{% static "img/icon_twitter.png" %}' alt='icon twitter' class='icon' width='32' height='32'>
                <img src='{% static "img/icon_github.png" %}' alt='icon github' class='icon' width='32' height='32'>
                <img src='{% static "img/icon_rss.png" %}' alt='icon rss' class='icon' width='32' height='32'>
            </div>

            <div class='social_2'>
                <figure class='col-6'>
                    <figcaption>made in</figcaption>
                    <img src='{% static "img/icon_peru.png" %}' alt="bandera del peru" height='24' width='36'>
                </figure>

                <figure class="col-6">
                    <figcaption>powered by</figcaption>
                    <img src='{% static "img/logo_django_200.png" %}' alt="logo django" height='24' width='58'>
                </figure>
            </div>
        </div>
    </div>
</footer>

uxlabs/templates/common/_header.html
{% load static %}
<header>
    <div class='header_container'>
        <div class="logo">
            <a href="{% url 'websites:home' %}">
                <img src='{% static "img/logo.png" %}' alt="logo uxlabs" width="200">
            </a>
        </div>

        <nav>
            <ul class='nav_list'>
                <li><a class='nav-link' href="{% url 'websites:home' %}">home</a></li>
                <li><a class='nav-link' href="{% url 'info:nosotros' %}">información</a></li>
                <li><a class='nav-link' href="{% url 'websites:websites' %}">galería</a></li>
                <li><a class='nav-link' href="{% url 'contacts:contacto' %}">contáctanos</a></li>
                <!--<li><a class='nav-link' href="{% url 'info:legal' %}">Términos y Condiciones</a></li>-->
            </ul>
        </nav>

        <div class='block-search'>
            <img class="icon-search" src='{% static "img/ic_search.svg" %}' alt="icono de busqueda">
            <input type='search' placeholder='buscar..'>
        </div>
    </div>
</header>

uxlabs/templates/contacts/contacto.html
{% extends 'common/_base.html' %}


{% block content %}

<h1>Contacto</h1>

{% if form.is_valid %}
    <p>Gracias por escribirnos, pronto lo contactaremos !</p>
{% else %}
    <form action='#' method="POST">
    {%  csrf_token %}
    {{ form.as_ul }}
    <input type="submit">
    </form>
{% endif %}
{% endblock content %}

uxlabs/templates/info/legal.html
{% extends 'common/_base.html' %}

{% block content %}
<h1>Términos y Condiciones</h1>

{% for seccion in secciones %}
    <h1>{{ seccion.titulo }}</h1>
    <div>{{ seccion.detalle }}</div>
{% endfor %}

{% endblock content %}

uxlabs/templates/info/nosotros.html
{% extends 'common/_base.html' %}

{% block content %}
<h1>Nosotros</h1>

{% for seccion in secciones %}
    <h1>{{ seccion.titulo }}</h1>
    <div>{{ seccion.detalle }}</div>
{% endfor %}

{% endblock content %}

uxlabs/templates/pure_pagination/pagination.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; Anterior </a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; Anterior</span>
    {% endif %}

    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">Siguiente &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">Siguiente &rsaquo;&rsaquo;</span>
    {% endif %}
</div>

uxlabs/templates/web/detalle.html
{% extends 'common/_base.html' %}

{% block content %}

<div>
    <h1>{{ web.nombre }}</h1>

    <h2>Detalle</h2>
    <div>{{ web.detalle }}</div>

    <h2>Enlace</h2>
    <div>{{ web.enlace }}</div>

    <div>
        <h2>Galería de imágenes</h2>

        {% for imagen in web.galeria.all%}
            <img src="{{ imagen.imagen.url }}" alt="{{ imagen.titulo }}" width='500'>
        {% endfor %}

    </div>
</div>
{% endblock content %}

uxlabs/templates/web/home.html
{% extends 'common/_base.html' %}
{% load static %}
{% load thumbnail %}

{% block classbody %}home{% endblock classbody %}

{% block content %}

<h1 class='main_descripcion'>Navega y encuentra websites que brindan una buena experiencia para el usuario</h1>

<blockquote class='main_quote'>"Piensa más, diseña menos" - Ellen Lupton</blockquote>

<section class='destacado'>
    <div class="columns">
        <div class='col-6'>
            {% thumbnail destacado.main_img.imagen '480x360' crop='top' as im %}
                <img src='{{ im.url }}' alt='destacado - {{ destacado.nombre }}'>
            {% endthumbnail %}

        </div>

        <div class='col-6'>
            <div class='header'>
                <h2>DESTACADO DEL DÍA</h2>
                <time datetime="{{ destacado.fecha_de_revision }}">{{ destacado.fecha_de_revision }}</time>
            </div>

            <div class='titulo'>{{ destacado.nombre }}</div>

            <div class='resumen'>
                {{ destacado.resumen }}
            </div>
        </div>
    </div>
</section>

{% for web in webs %}
    <h1>{{ web.nombre }}</h1>
    <div>{{ web.resumen|safe }}</div>
{% endfor %}
{% endblock content %}

uxlabs/templates/web/websites.html
{% extends 'common/_base.html' %}

{% block content %}
<h1>Websites</h1>

<div>
    <span>Categorías</span>

    <form action='#'>
        <select name='categoria'>
            <option value="">Todos</option>
            {% for tmp_categoria in categorias %}
                <option value='{{ tmp_categoria.nombre }}' {% if tmp_categoria.nombre == q_categoria %}selected{% endif %}>{{ tmp_categoria.nombre }}</option>
            {% endfor %}
        </select>

        <input type='submit' value='Enviar'>
    </form>
</div>

<div>
    <span>Buscador</span>
    <form action='{% url "websites:websites" %}'>
        <input name='q' type="search" placeholder='Ingrese el término de búsqueda' {% if q %} value='{{ q }}'{% endif %}>
        <input type='submit' value='Buscar'>
        <span>Ingrese al menos 3 caracteres</span>
    </form>
</div>

{% for web in lista_webs.object_list %}
    <h1><a href='{{ web.get_absolute_url }}'>{{ web.nombre }}</a></h1>
    <div>{{ web.resumen|safe }}</div>
{% endfor %}


<!-- paginación -->

<div id="pagination">
    {{ lista_webs.render }}
</div>
{% endblock content %}